import { useContext, useMemo } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";

import UserHome from "@components/home";
import { AuthContext } from "@context/AuthContext";
import Navbar from "@components/navbar";
import Footer from "@components/footer";

const Login = dynamic(() => import("@components/login"), { ssr: false });

export default function Home() {
  const { isAuthenticated } = useContext(AuthContext);

  const component = useMemo(() => {
    if (!isAuthenticated) return <Login />;

    return (
      <>
        <Navbar />
        <UserHome />
      </>
    );
  }, [isAuthenticated]);

  return (
    <>
      <Head>
        <title>Dummy app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {component}
      <Footer />
    </>
  );
}
